name: Linux

on: [push]

jobs:
  RyuJIT:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install clang zlib1g-dev libkrb5-dev libtinfo5
    - name: Build
      run: dotnet publish -r linux-x64 -c release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: RyuJIT
        path: bin\release\netcoreapp3.1\linux-x64\publish

  CPP:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get install clang zlib1g-dev libkrb5-dev libtinfo5
    - name: Build
      run: dotnet publish -r linux-x64 -c release -p:NativeCodeGen=cpp
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CPP
        path: bin\release\netcoreapp3.1\linux-x64\publish
