name: Win

on: [push]

jobs:
  RyuJIT:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: dotnet publish -r win-x64 -c release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: RyuJIT
        path: bin\Release\netcoreapp3.1\win-x64\publish

  CPP:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v1
    - name: Build
      run: dotnet publish -r win-x64 -c release -p:NativeCodeGen=cpp
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CPP
        path: bin\Release\netcoreapp3.1\win-x64\publish
